# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

# gem "rails"

gem "webauthn", "~> 2.5"
gem "roda", "~> 3.43"

gem "sequel", "~> 5.43"
