<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerIs2ME99\Drift_KernelDevContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerIs2ME99/Drift_KernelDevContainer.php') {
    touch(__DIR__.'/ContainerIs2ME99.legacy');

    return;
}

if (!\class_exists(Drift_KernelDevContainer::class, false)) {
    \class_alias(\ContainerIs2ME99\Drift_KernelDevContainer::class, Drift_KernelDevContainer::class, false);
}

return new \ContainerIs2ME99\Drift_KernelDevContainer([
    'container.build_hash' => 'Is2ME99',
    'container.build_id' => '32d4ced5',
    'container.build_time' => 1619098605,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerIs2ME99');
