<?php

namespace ContainerIs2ME99;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDrift_FilesystemService extends Drift_KernelDevContainer
{
    /*
     * Gets the public 'drift.filesystem' shared service.
     *
     * @return \React\Filesystem\Filesystem
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/react/filesystem/src/FilesystemInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/react/filesystem/src/Filesystem.php';

        return $container->services['drift.filesystem'] = \React\Filesystem\Filesystem::create(($container->services['reactphp.event_loop'] ?? $container->get('reactphp.event_loop', 1)));
    }
}
