<?php

namespace ContainerIs2ME99;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMercureService extends Drift_KernelDevContainer
{
    /*
     * Gets the public 'App\Controller\Mercure' shared autowired service.
     *
     * @return \App\Controller\Mercure
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Controller/Mercure.php';

        return $container->services['App\\Controller\\Mercure'] = new \App\Controller\Mercure();
    }
}
